-- ============================================
-- ECOMMERCE DATA ANALYSIS - COMPLETE SQL SCRIPT
-- Dataset: Online Retail Dataset (Kaggle)
-- Tool: SQLite (DB Browser)
-- ============================================

-- ============================================
-- CREATE TABLES
-- ============================================

-- Create customers table
CREATE TABLE customers AS
SELECT DISTINCT CustomerID, Country
FROM data
WHERE CustomerID != '';

-- Create products table
CREATE TABLE products AS
SELECT DISTINCT StockCode, Description, UnitPrice
FROM data
WHERE Description != '?' 
AND UnitPrice > 0;

-- Create orders table
CREATE TABLE orders AS
SELECT InvoiceNo, CustomerID, StockCode, Quantity, InvoiceDate
FROM data
WHERE CustomerID != ''
AND Quantity > 0;

-- ============================================
-- CHECK NULL VALUES
-- ============================================

-- Check for NULL/missing values in all columns
SELECT
    COUNT(*) - COUNT(InvoiceNo) AS Null_InvoiceNo,
    COUNT(*) - COUNT(CustomerID) AS Null_CustomerID,
    COUNT(*) - COUNT(Description) AS Null_Description,
    COUNT(*) - COUNT(Quantity) AS Null_Quantity,
    COUNT(*) - COUNT(UnitPrice) AS Null_UnitPrice,
    COUNT(*) - COUNT(Country) AS Null_Country
FROM data;

-- ============================================
-- BASIC SELECT, WHERE, ORDER BY
-- ============================================

-- High Quantity Orders Sorted by Date
-- Business Insight: Which transactions involved bulk purchases and when
SELECT 
    InvoiceNo,
    CustomerID,
    Quantity,
    InvoiceDate
FROM orders
WHERE Quantity > 10
AND CustomerID IS NOT NULL
ORDER BY InvoiceDate DESC
LIMIT 20;

-- ============================================
-- GROUP BY + AGGREGATE FUNCTIONS
-- ============================================

-- Total Revenue Generated by Each Country
-- Business Insight: Which country is the biggest market
SELECT 
    c.Country,
    COUNT(DISTINCT o.InvoiceNo) AS TotalOrders,
    SUM(o.Quantity * p.UnitPrice) AS TotalRevenue,
    ROUND(AVG(o.Quantity * p.UnitPrice), 2) AS AvgOrderValue
FROM orders o
JOIN customers c ON o.CustomerID = c.CustomerID
JOIN products p ON o.StockCode = p.StockCode
WHERE c.Country IS NOT NULL
GROUP BY c.Country
ORDER BY TotalRevenue DESC;

-- ============================================
-- INNER JOIN
-- ============================================

-- Complete Order Details with Customer Location and Product Name
-- Business Insight: Full picture of each transaction
SELECT 
    o.InvoiceNo,
    c.Country,
    COALESCE(p.Description, 'Unknown Product') AS Description,
    o.Quantity,
    COALESCE(p.UnitPrice, 0) AS UnitPrice,
    ROUND(o.Quantity * COALESCE(p.UnitPrice, 0), 2) AS TotalAmount
FROM orders o
INNER JOIN customers c ON o.CustomerID = c.CustomerID
INNER JOIN products p ON o.StockCode = p.StockCode
LIMIT 20;

-- ============================================
-- LEFT JOIN
-- ============================================

-- All Customers Including Those With No Orders
-- Business Insight: Inactive customers for marketing campaigns
SELECT 
    c.CustomerID,
    c.Country,
    COALESCE(o.InvoiceNo, 'No Orders') AS InvoiceNo
FROM customers c
LEFT JOIN orders o ON c.CustomerID = o.CustomerID
ORDER BY o.InvoiceNo DESC
LIMIT 20;

-- ============================================
-- SUBQUERY
-- ============================================

-- Customers Who Buy More Than Average Quantity
-- Business Insight: High volume buyers compared to typical customer
SELECT 
    CustomerID,
    ROUND(AVG(Quantity), 2) AS AvgQuantity
FROM orders
WHERE CustomerID IS NOT NULL
GROUP BY CustomerID
HAVING AVG(Quantity) > (
    SELECT AVG(Quantity) 
    FROM orders 
    WHERE Quantity > 0
)
ORDER BY AvgQuantity DESC
LIMIT 20;

-- ============================================
-- TOP CUSTOMERS BY REVENUE
-- ============================================

-- Top 10 Customers by Total Spending and Average Order Value
-- Business Insight: VIP customer list
SELECT 
    o.CustomerID,
    c.Country,
    COUNT(DISTINCT o.InvoiceNo) AS TotalOrders,
    SUM(o.Quantity * p.UnitPrice) AS TotalSpent,
    ROUND(AVG(o.Quantity * p.UnitPrice), 2) AS AvgOrderValue
FROM orders o
JOIN customers c ON o.CustomerID = c.CustomerID
JOIN products p ON o.StockCode = p.StockCode
WHERE o.CustomerID IS NOT NULL
GROUP BY o.CustomerID, c.Country
ORDER BY TotalSpent DESC
LIMIT 10;

-- ============================================
-- CREATE VIEW
-- ============================================

-- High Value Customers View
-- Business Insight: Reusable saved list of premium customers
CREATE VIEW highest_value_customers AS
SELECT 
    c.CustomerID,
    c.Country,
    COUNT(DISTINCT o.InvoiceNo) AS TotalOrders,
    ROUND(SUM(o.Quantity * p.UnitPrice), 2) AS TotalRevenue
FROM orders o
JOIN customers c ON o.CustomerID = c.CustomerID
JOIN products p ON o.StockCode = p.StockCode
WHERE o.CustomerID IS NOT NULL
GROUP BY c.CustomerID, c.Country
HAVING TotalRevenue > 1000;
SELECT * FROM highest_value_customers
ORDER BY TotalRevenue DESC;

-- ============================================
-- INDEXES FOR OPTIMIZATION
-- ============================================

-- Add Indexes to Speed Up Queries
-- Optimizes searches on frequently queried columns
CREATE INDEX idx_customerid ON orders(CustomerID);
CREATE INDEX idx_stockcode ON orders(StockCode);
CREATE INDEX idx_invoicedate ON orders(InvoiceDate);


